
--EJERCICIO 3

ALTER TABLE TRABAJADOR
DROP constraint fk_trabajador_ong;

ALTER TABLE PROYECTO
DROP CONSTRAINT FK_PROYECTO_ONG;

ALTER TABLE ONG
DROP CONSTRAINT FK_ONG_SOCIO; 

ALTER TABLE COLABORACION
DROP CONSTRAINT FK_COLABORACION_ONG; 

ALTER TABLE PARTICIPACION
DROP CONSTRAINT FK_PARTICIPACION_ONG;

ALTER TABLE PARTICIPACION
DROP CONSTRAINT FK_PARTICIPACION_TRABAJADOR;

DELETE FROM ONG WHERE CODIGO=1111111111;
DELETE FROM PARTICIPACION WHERE TRABAJADOR IN (SELECT NIF
											FROM TRABAJADOR
											WHERE ONG=1111111111);
DELETE FROM PARTICIPACION WHERE ONG=1111111111;
DELETE FROM TRABAJADOR WHERE ONG=1111111111;
DELETE FROM COLABORACION WHERE ONG=1111111111;
DELETE FROM PROYECTO WHERE ONG=1111111111;


ALTER TABLE TRABAJADOR
ADD constraint fk_trabajador_ong FOREIGN KEY(ONG) REFERENCES ong(CODIGO);

ALTER TABLE PROYECTO
ADD CONSTRAINT FK_PROYECTO_ONG FOREIGN KEY(ONG) REFERENCES ONG(CODIGO);

ALTER TABLE ONG
ADD CONSTRAINT FK_ONG_SOCIO FOREIGN KEY(RESPONSABLE) REFERENCES TRABAJADOR(NIF); 

ALTER TABLE COLABORACION
ADD CONSTRAINT FK_COLABORACION_ONG FOREIGN KEY (ONG) REFERENCES ONG(CODIGO); 

ALTER TABLE PARTICIPACION
ADD CONSTRAINT FK_PARTICIPACION_ONG FOREIGN KEY(ONG) REFERENCES ONG(codigo);

ALTER TABLE PARTICIPACION
ADD CONSTRAINT FK_PARTICIPACION_TRABAJADOR FOREIGN KEY (trabajador) REFERENCES trabajador(nif);


