
--EJERCICIO 6

DROP VIEW VOLUNTARIO;
 
 CREATE VIEW VOLUNTARIO (NIF,NOMBRE,ONG,FECHAINGRESO,PROFESION,HORAS)
AS    SELECT NIF,NOMBRE,ONG,FECHAINGRESO,PROFESION,HORAS 
      FROM TRABAJADOR T
	  WHERE T.ES_VOLUNTARIO='S';
	  
SELECT *
FROM VOLUNTARIO;


UPDATE VOLUNTARIO SET HORAS=HORAS*1.1;

SELECT *
FROM VOLUNTARIO;


DROP VIEW VOLUNTARIO;

CREATE VIEW VOLUNTARIO (nif,nombre,ong,PROFESION,HORAS)
AS 	SELECT nif,nombre,ong,PROFESION,HORAS
	FROM TRABAJADOR T
	WHERE T.ES_VOLUNTARIO='S';

select * 
from VOLUNTARIO;

