
--EJERCICIO 5
DROP TABLE CONTRATADO CASCADE CONSTRAINT;

CREATE TABLE CONTRATADO AS SELECT NIF,NOMBRE,ONG,FECHAINGRESO,SUELDO
                           FROM TRABAJADOR
						   WHERE ES_VOLUNTARIO='N';

ALTER TABLE CONTRATADO
ADD CONSTRAINT FK_CONTRATADO_ONG FOREIGN KEY (ONG) REFERENCES ONG(CODIGO);
ALTER TABLE CONTRATADO
ADD CONSTRAINT FK_CONTRATADO_PARTICIPACION FOREIGN KEY (NIF) REFERENCES TRABAJADOR(NIF);

SELECT *
FROM CONTRATADO;

ALTER TABLE CONTRATADO
ADD CONSTRAINT CK_CONTRATADO CHECK (SUELDO>=1000 AND SUELDO<=3000);


ALTER TABLE CONTRATADO 
ADD NUMPARTICIPACION NUMBER (4);
UPDATE CONTRATADO C SET NUMPARTICIPACION= (select count(*) num
											from participacion P
											WHERE C.NIF=P.TRABAJADOR);

SELECT *
FROM CONTRATADO;

aLTER TABLE CONTRATADO DROP COLUMN NUMPARTICIPACION;
SELECT * 
FROM CONTRATADO;


