
--EJERCICIO 2
ALTER TABLE PARTICIPACION
drop CONSTRAINT FK_PARTICIPACION_TRABAJADOR;
ALTER TABLE ONG
drop CONSTRAINT FK_ONG_SOCIO ;

update trabajador set nif=00000008 where nif=00000001;
update participacion set trabajador=00000008 where trabajador=00000001;
update ong set responsable=00000008 where responsable=00000001;
ALTER TABLE ONG
ADD CONSTRAINT FK_ONG_SOCIO FOREIGN KEY(RESPONSABLE) REFERENCES TRABAJADOR(NIF);
ALTER TABLE PARTICIPACION
ADD CONSTRAINT FK_PARTICIPACION_TRABAJADOR FOREIGN KEY (trabajador) REFERENCES trabajador(nif);

